---
groups:
  - name: web
    jobs:
      - unit

resources:
  - name: web
    type: git
    source:
      uri: git@github.com:phogolabs/web.git
      branch: master
      private_key: {{git-private-key}}

jobs:
  - name: unit
    plan:
      - get: web
        trigger: true
      - task: unit
        file: web/ci/task/unit.yml
